### YamlMime:FAQ
metadata:
  title: Nejčastější dotazy k zabezpečení
  description: Získejte aktuální informace o běžných bezpečnostních dotazech a odpovědích týkajících se zařízení HoloLens hybridní realitou.
  ms.assetid: bd55ecd1-697a-4b09-8274-48d1499fcb0b
  author: pawinfie
  ms.author: pawinfie
  ms.date: 02/19/2020
  keywords: hololens, Windows Mixed Reality, security
  ms.prod: hololens
  ms.sitesec: library
  ms.topic: article
  audience: ITPro
  ms.localizationpriority: medium
  ms.custom:
  - CI 111456
  - CSSTroubleshooting
  manager: bradke
  ms.openlocfilehash: 108f2e4c0aa9af251ecb6bc5185c7803ae51b5f7
  ms.sourcegitcommit: e9f746aa41139859edc12fbc21f926c9461da4b3
  ms.translationtype: MT
  ms.contentlocale: cs-CZ
  ms.lasthandoff: 09/13/2021
  ms.locfileid: "126032356"
title: Nejčastější dotazy HoloLens zabezpečení (1. generace)
summary: ''
sections:
- name: Ignorováno
  questions:
  - question: >
      Jakou úroveň ochrany dat nabízí HoloLens 1?
    answer: >
      * Viz [HoloLens šifrování nástrojem BitLocker (1. generace).](hololens1-encryption.md)
  - question: >
      Jaký typ bezdrátové sítě se používá?
    answer: >
      * 802.11ac a Bluetooth 4.1 LE
  - question: >
      Jaký typ architektury je začleněný?  Například point-to-point, mesh nebo něco jiného?
    answer: >
      * Wi-Fi lze použít v režimu infrastruktury ke komunikaci s ostatními bezdrátovými přístupové body.

      * Bluetooth můžete použít ke vzájemné vzájemné spolupráci mezi více HoloLens, pokud to aplikace zákazníků podporuje, nebo s jinými Bluetooth zařízeními.
  - question: >
      Co je ID FCC?
    answer: >
      * C3K1688
  - question: >
      S jakým rozsahem četnosti a kanály zařízení pracuje a je konfigurovatelné?
    answer: >
      * Wi-Fi: Rozsah četnosti není konfigurovatelný uživatelem a závisí na zemi použití. V USA používá Wi-Fi kanály o frekvenci 2,4 GHz (1–11) i kanály 5 GHz (36–64, 100–165).

      * Bluetooth: Bluetooth používá standardní rozsah 2,4–2,48 GHz.
  - question: >
      Může zařízení povolit nebo blokovat konkrétní frekvence?
    answer: >
      * Uživatel/zařízení to nemůže ovládat.
  - question: >
      Jaká je úroveň napájení pro přenos i příjem? Jde to upravit? Jaký je rozsah operací?
    answer: >
      * Naše standardy pro testování emisí najdete [tady.](https://fccid.io/C3K1688) Rozsah operací je vysoce závislý na přístupových bodech a prostředích , ale přibližně odpovídá jiným vysoce kvalitním telefonům, tabletem nebo počítačům.
  - question: >
      Jaký je provozní cyklus nebo doba platnosti pro normální provoz?
    answer: >
      * 2–3 hodiny aktivního použití a až dva týdny pohotovostního režimu

      * Doba životnosti baterie není k dispozici.
  - question: >
      Co je chování při přenosu a příjmu, když nástroj není v dosahu?
    answer: >
      * HoloLens/příjem se řídí standardním vzorem Wi-Fi/Bluetooth sítě. Na hranici svého rozsahu si pravděpodobně všimnete, že vstup je neskončený, dokud se úplně neodpojí, ale jakmile se vrátíte do dosahu, měl by se rychle znovu připojit.
  - question: >
      Co je hustota nasazení na čtvereční stopu?
    answer: >
      * To závisí na vaší síťové infrastruktuře.
  - question: >
      Může zařízení používat infrastrukturu jako klienta?
    answer: >
      * Yes
  - question: >
      Jaký protokol se používá?
    answer: >
      * HoloLens nepoužívejte žádné proprietární protokoly.
  - question: >
      Frekvence aktualizací operačního systému – Jaká je frekvence aktualizací operačního systému pro HL?  Existuje nastavený plán?  Vymyšluje Microsoft opravy zabezpečení podle potřeby atd.
    answer: >
      * Microsoft poskytuje aktualizace operačního systému tak HoloLens aby byly úplně stejné jako pro Windows 10. Za rok obvykle existují dvě hlavní aktualizace, jedna na nulu, jedna na poklesu. Protože HoloLens je Windows zařízení, je koncept aktualizace stejný jako u všech ostatních Windows zařízení. Microsoft vydává opravy zabezpečení podle potřeby a dodržuje stejný koncept jako na jakémkoli jiném Windows zařízení.
  - question: >
      Zabezpečení operačního systému – Jaké jsou možnosti pro zabezpečení operačního systému?  Můžeme odebrat nebo vypnout nepotřebné aplikace nebo služby?
    answer: >
      * HoloLens se chová jako smartphone. Je srovnatelný s jinými moderními Windows zařízeními. HoloLens můžete spravovat pomocí Microsoft Intune nebo jiných moderních Správa zařízení, jako jsou MobileIron, Airwatch nebo Soti. V těchto systémech pro správu můžete nastavit zásady zabezpečení pro zařízení a pro jejich zabezpečení. Existuje také možnost odstranit všechny nepotřebné aplikace, pokud chcete.
  - question: >
      Jak se budou spravovat a aktualizovat softwarové aplikace? Jaký ovládací prvek máme k definování toho, které aplikace se načítá a jak se aktualizují aplikace pro aplikace, které se v Microsoft Storu nachází?
    answer: >
      * HoloLens získá softwarové aplikace jenom prostřednictvím Windows Store. Je možné nainstalovat pouze balíčky aplikací Appx, které jsou vyvinuty pro použití HoloLens. Můžete to vidět na Microsoft Store s malým logem vedle aplikace, která zobrazuje HoloLens zařízení. Všechny ovládací prvek, který máte nad s právy pro správu aplikací pro Store, platí také pro HoloLens. Můžete použít koncept oficiálního obchodu nebo obchodu pro firmy. Aplikace je možné načíst bokem (ruční proces načtení aplikace na zařízení Windows) nebo je možné je spravovat prostřednictvím MDM, aby se aplikace v případě potřeby automaticky stáhly ze Storu.
  - question: >
      Jaká je frekvence aktualizací aplikací ve Storu pro HoloLens?
    answer: >
      * Vzhledem k tomu, že dodržujeme stejný koncept Microsoft Store a načtou aplikace odtud, je cyklus aktualizace určen vývojářem aplikace. Všechny možnosti správy, které potřebujete k řízení mechanismu aktualizace v obchodě, platí také HoloLens nástroje .
  - question: >
      Existuje možnost zabezpečeného spouštění pro HoloLens?
    answer: >
      * Yes
  - question: >
      Je možné zakázat nebo odpojit podporu periferních zařízení od zařízení?
    answer: >
      * Yes
  - question: >
      Je možné řídit nebo zakázat používání portů na zařízení?
    answer: >
      * Konektor HoloLens obsahuje jenom dva porty (jeden pro vychytáky a jeden pro účtování nebo připojení k počítačům). Kvůli funkčnosti a důvodům obnovení není možné port zakázat.
  - question: >
      Antivirový program, detekce koncových bodů, IPS, seznam povolení řízení aplikací – Libovolná možnost spouštět antivirový program, detekci koncových bodů, IPS, seznam povolení řízení aplikací atd.
    answer: >
      * Windows Holographic for Business (komerční sada) podporuje Windows Defender Smart Screen. Pokud by antivirová společnost vytvořila aplikaci a publikoval ji na Univerzální Windows Platform, mohla by se stáhnout na HoloLens. V současné době to pro společnost HoloLens.

      * Povolení aplikací je možné pomocí Microsoft Enterprise Storu, kde si můžete vybrat jenom ty konkrétní aplikace, které je možné stáhnout. Prostřednictvím MDM můžete také uzamknout, které konkrétní aplikace je možné spouštět nebo dokonce zobrazit na zařízení.
  - question: >
      Je možné umístit zařízení do karantény od prod network, dokud ho delší dobu ne aktualizačním?  Například Zařízení bylo po dobu (šest měsíců) v zásuvce a neobdrželo žádné aktualizace, opravy atd.  Když se pokusí připojit k síti, můžeme ji označit příznakem a říct, že musíte před stížností na připojení k síti aktualizovat v jiné síti.
    answer: >
      * To je něco, co se může spravovat na úrovni infrastruktury pomocí MDM nebo na serveru na úrovni serveru. Zařízení může být označeno jako nevyhovující, pokud nesplňuje zadanou verzi aktualizace.
  - question: >
      Zahrnuje Microsoft nějaké zadní vratky nebo přístup ke službám, které microsoftu umožňují připojit se k zařízení a sdílet obrazovku nebo vzdálenou podporu libovolně?
    answer: >
      * No
  - question: >
      Při vygenerování certifikátu PKI pro důvěryhodnou komunikaci chceme, aby se certifikát vygeneroval na zařízení, abychom věděli, že je jenom na tomto zařízení, je pro toto zařízení jedinečný a nelze ho exportovat ani použít k zosobnění zařízení. Platí to pro HoloLens? Pokud ne, může dojít k omezení rizik?
    answer: >-
      * CsR pro SCEP se generuje na samotném zařízení. Intune a místní konektor SCEP pomáhají zabezpečit samotné požadavky přidáním a ověřením řetězce výzvy odeslaného klientovi.

      * Od HoloLens (1. generace a 2. generace) mají modul TPM, budou tyto certifikáty uložené v modulu TPM a nedaří se je extrahovat. Navíc i v případě, že by se mohly extrahovat, nešlo ověřit řetězce výzvy na jiném zařízení, takže certifikáty nebo klíče se na různých zařízeních nepoužitelné nepoužitelné.
